version: '3.8'

services:
  pomodoro-app:
    image: gertjanhon/pomodoroklok
    ports:
      - "3124:3000"
    container_name: pomodoroklok
    restart: unless-stopped

  pomodoro-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5179:8080"
    container_name: pomodoroklok-api
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
